# Generated by Django 3.0.8 on 2020-08-02 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_subject', models.CharField(help_text='Model para armazenar as disciplinas escolares no banco de dados', max_length=30, verbose_name='Disciplina escolar')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Nome')),
                ('sur_name', models.CharField(max_length=40, verbose_name='Sobrenome')),
                ('mothers_name', models.CharField(max_length=50, verbose_name='Nome da mãe')),
                ('fathers_name', models.CharField(max_length=50, verbose_name='Nome do pai')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('grade', models.CharField(choices=[('N1 - Educação Infantil', 'N1 - Educação Infantil'), ('N2 - Educação Infantil', 'N2 - Educação Infantil'), ('N3 - Educação Infantil', 'N3 - Educação Infantil'), ('1º Ano - Ensino Fundamental', '1º Ano - Ensino Fundamental'), ('2º Ano - Ensino Fundamental', '2º Ano - Ensino Fundamental'), ('3º Ano - Ensino Fundamental', '3º Ano - Ensino Fundamental'), ('4º Ano - Ensino Fundamental', '4º Ano - Ensino Fundamental'), ('5º Ano - Ensino Fundamental', '5º Ano - Ensino Fundamental'), ('6º Ano - Ensino Fundamental', '6º Ano - Ensino Fundamental'), ('7º Ano - Ensino Fundamental', '7º Ano - Ensino Fundamental'), ('8º Ano - Ensino Fundamental', '8º Ano - Ensino Fundamental'), ('9º Ano - Ensino Fundamental', '9º Ano - Ensino Fundamental'), ('1º Ano - Ensino Médio', '1º Ano - Ensino Médio'), ('2º Ano - Ensino Médio', '2º Ano - Ensino Médio'), ('3º Ano - Ensino Médio', '3º Ano - Ensino Médio')], max_length=50, verbose_name='Série')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_grade', models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Nota')),
                ('school_period', models.CharField(help_text='Se primeiro bimestre, segundo bimestre, etc...', max_length=20, verbose_name='Período do ano')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='Estudante')),
                ('subject', models.ForeignKey(help_text='Disciplina escolar relacionada ao estudante', on_delete=django.db.models.deletion.DO_NOTHING, to='core.SchoolSubject', verbose_name='Disciplina escolar')),
            ],
        ),
        migrations.CreateModel(
            name='StudentApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField(help_text='Se o estudante passar de ano, o valor será True, se não, False', verbose_name='Estudante aprovado')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2020)], verbose_name='Ano')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student', verbose_name='Estudante')),
            ],
        ),
    ]
