language: python
python:
  - 3.8
script:
  - python -m venv .venv
  - source .venv/bin/activate
install:
  - pip install -q -r requirements.txt
script:
  - flake8
  - pytest --cov=pyjobschallenge
after_success:
  - codecov